name: Build and Deploy to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Add host to known_hosts
        env:
          HOST: ${{ secrets.HETZNER_HOST }}
          PORT: ${{ secrets.HETZNER_PORT }}
        run: |
          mkdir -p ~/.ssh
          if [ -z "$PORT" ]; then PORT=22; fi
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy via SFTP (lftp mirror) using SSH key
        env:
          HOST: ${{ secrets.HETZNER_HOST }}
          USER: ${{ secrets.HETZNER_USER }}
          REMOTE_PATH: ${{ secrets.HETZNER_REMOTE_PATH }}
          PORT: ${{ secrets.HETZNER_PORT }}
        run: |
          # defaults
          if [ -z "${PORT}" ]; then PORT=22; fi
          if [ -z "${REMOTE_PATH}" ]; then echo "REMOTE_PATH is not set"; exit 1; fi

          echo "Writing private key to temporary file"
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.HETZNER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          echo "Installing lftp"
          sudo apt-get update -y
          sudo apt-get install -y lftp

          echo "Checking SSH key auth (BatchMode)"
          ssh -i ~/.ssh/deploy_key -o BatchMode=yes -p "${PORT}" "${USER}@${HOST}" 'echo AUTH_OK' || { echo "Key authentication failed for ${USER}@${HOST}:${PORT}"; exit 1; }

          echo "Uploading ./dist -> sftp://${USER}@${HOST}:${PORT}${REMOTE_PATH} using lftp mirror"
          # Use lftp with SFTP and the ssh identity file; mirror -R will upload directory recursively and delete remote extraneous files
          lftp -e "set sftp:connect-program 'ssh -a -x -i ~/.ssh/deploy_key -p ${PORT}'; open sftp://${USER}@${HOST}; mirror -R --delete --verbose ./dist ${REMOTE_PATH}; bye"

          echo "SFTP upload finished"

          echo "Removing temporary private key"
          shred -u ~/.ssh/deploy_key || rm -f ~/.ssh/deploy_key || true
        shell: bash
